version: "3"
services:
  php:
    build: docker/php
    volumes:
      - .:/app:cached

      # for xdebug
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # end for xdebug
    working_dir: /app
    container_name: symfony_elastic_search_php
#    depends_on:
#      - mysql

  nginx:
    image: nginx:1.15.0
    ports:
      - 127.0.0.1:${NGINX_PORT}:80
    volumes:
      - .:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    container_name: symfony_elastic_search_nginx
    depends_on:
      - php
